let game = new EscapeGame({
	debug: true,
	sprites: [
		"./img/fox.png",
		"./img/cleric.png",
		"./img/cave_ceiling.png",
		"./img/elf.png",
		"./img/floor.png",
		"./img/background.png",
		"./img/necromancer.png",
		"./img/dwarf.png",
		"./img/boulder.png",
		"./img/magicdoor.png",
		"./img/toxicgas.png",
		"./img/soulpit.png",
		"./img/icons/Vader.png",
		"./img/icons/Bill.png",
		"./img/icons/Ylvis.png",
		"./img/icons/Brody.png",
		"./img/icons/Jessica.png",
		"./img/icons/Rupert.png",
		"./img/icons/Narrator.png",
		"./img/Record.png"
	],
	sprite_mapping: {
		'./img/floor.png': 'floor',
		'./img/background.png': 'background',
		'./img/fox.png': 'fox',
		'./img/cave_ceiling.png': 'cave_ceiling',
		'./img/cleric.png': 'cleric',
		'./img/elf.png': 'elf',
		'./img/necromancer.png': 'necromancer',
		'./img/dwarf.png': 'dwarf',
		'./img/boulder.png': 'boulder',
		'./img/toxicgas.png': 'toxicgas',
		'./img/magicdoor.png': 'magicdoor',
		'./img/soulpit.png': 'soulpit',
		'./img/icons/Vader.png': 'VaderIcon',
		'./img/icons/Bill.png': 'BillIcon',
		'./img/icons/Ylvis.png': 'YlvisIcon',
		'./img/icons/Brody.png': 'BrodyIcon',
		'./img/icons/Jessica.png': 'JessicaIcon',
		'./img/icons/Rupert.png': 'RupertIcon',
		'./img/icons/Narrator.png': 'NarratorIcon',
		'./img/Record.png': 'Record',
	}
})
game.run()